services:
  web:
    image: php:8.5-apache
    container_name: php_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/apache.conf:/etc/apache2/sites-available/000-default.conf
    restart: always